-- 코드를 입력하세요
SELECT A.APNT_NO, B.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM   APPOINTMENT A,
       PATIENT     B,
       DOCTOR      C
WHERE  A.MCDP_CD = 'CS' --흉부외과
AND    A.APNT_CNCL_YN = 'N'
AND    TO_CHAR(A.APNT_YMD,'YYYYMMDD') = '20220413'
AND    A.PT_NO        = B.PT_NO
AND    A.MDDR_ID      = C.DR_ID
ORDER BY APNT_YMD