-- 코드를 입력하세요
# 베낌
WITH RECURSIVE TIME AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
        FROM TIME
        WHERE HOUR < 23
)
SELECT T.HOUR, COUNT(ANIMAL_ID) AS COUNT
    FROM TIME T
    LEFT JOIN (SELECT *, HOUR(DATETIME) AS HOUR
            FROM ANIMAL_OUTS) O
      ON T.HOUR = O.HOUR
    GROUP BY 1
    ORDER BY 1

# SELECT * FROM ANIMAL_OUTS